train: /Users/cheekeanchan/Dev/smart_passage/src/spl_data/processed/train/images
val: /Users/cheekeanchan/Dev/smart_passage/src/spl_data/processed/valid/images
test: /Users/cheekeanchan/Dev/smart_passage/src/spl_data/processed/test/images

nc: 5
# names: ['person', 'child', 'peopleWithwheelchair', 'wheelchair', 'luggage', 'cardboard']
names: ['person', 'peopleWithwheelchair', 'wheelchair', 'luggage', 'cardboard']
