video:
  source: "rtsp://service:Thales1$8o8@192.168.100.108:554/live"
  # source: "./static/backup/luggage.mp4"
  save_video: True
  plot_roi: True
  model_detect: True
  output_file_name: "./static/test_video/passenger.avi"
  font_size: 3
  mm_per_pixel: 1.85
  trigger_distance: 100
  stay_limit: 2
  img_sz:
  - 1280
  - 720
gate_roi:
  left: 40
  top: 640
  right: 1250
  bottom: 680
  left-safety: 380
  right-safety : 780
object_tracker:
  reid_weights: "./weights/osnet_x0_25_msmt17.pt"
  tracking_method: "deepocsort" 
  tracking_config: "./trackers/deepocsort/configs/deepocsort.yaml"
model:
  # model_name: "./weights/yolov8n.pt"
  model_name: "google/owlvit-base-patch32"
  conf_thres: 0.05
  iou_thres: 0.3
  max_det: 1000
  device: ""
  agnostic_nms: False
  classes: 
    - "person"
    - "old folk"
    - "kid"
    - "suitcase"
    - "wheelchair"
    - "luggage"
    - "baggage"
    - "box"
    - "stroller"
    - "trolley"
    - "object"
    # - "chair" 
    # - 0
    # - 2
    # - 9
    # - 12
    # - 13
    # - 20
    # - 24
    # - 38
    # - 39
    # - 46
    # - 47
    # - 52
    # - 58
    # - 120
    # - 124
    # - 129
    # - 130
    # - 192
