video:
  source: "rtsp://service:Thales1$8o8@192.168.100.108:554/live"
  # source: "./static/backup/luggage.mp4"
  save_video: False
  plot_roi: True
  model_detect: False
  output_file_name: "./static/test_video/passenger.avi"
  font_size: 1
  mm_per_pixel: 1.85
  trigger_distance: 100
  stay_limit: 30
  img_sz:
  - 640
  - 640
gate_roi:
  left: 20
  top: 590
  right: 620
  bottom: 620
  left-safety: 180
  right-safety : 400
object_tracker:
  reid_weights: "./weights/osnet_x0_25_msmt17.pt"
  tracking_method: "deepocsort" 
  tracking_config: "./trackers/deepocsort/configs/deepocsort.yaml"
model:
  model_name: "yolo_nas_s"
  conf_thres: 0.3
  iou_thres: 0.5
  max_det: 1000
  device: ""
  agnostic_nms: False
  classes: 
    - 'person'
    - 'bike'
    - 'wheelchair'
    - 'luggage'
    - 'cardboard'